name: silo_common
description: Common interfaces for silo orm
version: 1.0.0
repository: https://github.com/Eghosa-Osayande/silo
issue_tracker: https://github.com/Eghosa-Osayande/silo/issues
homepage: https://github.com/Eghosa-Osayande/silo
# documentation: https://github.com/Eghosa-Osayande/silo/docs

topics:
  - silo
  - orm
  - database
  - sqlite
  - sql
  

environment:
  sdk: ^3.6.0


dev_dependencies:
  lints: ^5.0.0
