name: silo_sqflite
description: Sqflite driver for Silo ORM
version: 0.0.1-dev.1
repository: https://github.com/Eghosa-Osayande/silo
issue_tracker: https://github.com/Eghosa-Osayande/silo/issues
homepage: https://github.com/Eghosa-Osayande/silo
# documentation: https://github.com/Eghosa-Osayande/silo/docs

topics:
  - orm
  - database
  - sqflite
  - sqlite3
  

environment:
  sdk: ^3.6.0

dependencies:
  silo: ^1.0.0
  sqflite: ^2.4.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
