name: silo
description: Silo ORM
version: 1.0.0
repository: https://github.com/Eghosa-Osayande/silo
issue_tracker: https://github.com/Eghosa-Osayande/silo/issues
homepage: https://github.com/Eghosa-Osayande/silo
# documentation: https://github.com/Eghosa-Osayande/silo/docs

topics:
  - silo
  - orm
  - database
  - sqlite
  - sql
  

environment:
  sdk: ^3.6.0

dependencies:
  sqlite_async: ^0.11.5
  sqlite3_flutter_libs: ^0.5.30
  silo_common: ^1.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
