name: silo
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

dependencies:
  sqlite3: ^2.7.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
