name: silo
description: A lightweight ORM-like library for Dart built on SQLite with key-value and SQL query support.
version: 1.0.0
repository: https://github.com/Eghosa-Osayande/silo
issue_tracker: https://github.com/Eghosa-Osayande/silo/issues
homepage: https://github.com/Eghosa-Osayande/silo
# documentation: https://github.com/Eghosa-Osayande/silo/docs

topics:
  - silo
  - orm
  - database
  - sqlite
  - sql

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  sqlite_async: ^0.11.5
  sqlite3_flutter_libs: ^0.5.30
  silo_common: ^1.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
