name: silo_sqlite3
description: Sqlite3 driver for Silo ORM
version: 0.0.1-dev.1
repository: https://github.com/Eghosa-Osayande/silo
issue_tracker: https://github.com/Eghosa-Osayande/silo/issues
homepage: https://github.com/Eghosa-Osayande/silo
# documentation: https://github.com/Eghosa-Osayande/silo/docs

topics:
  - orm
  - database
  - sql
  - sqlite3
  

environment:
  sdk: ^3.6.0

dependencies:
  silo: ^1.0.0
  sqlite3: ^2.7.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
